# Generated by Django 5.0.14 on 2026-06-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentsummary_groupmessage_studygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
